name: "CI"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'microsoft'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test